name: Build container
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: danielstoehr/raspberry-home:latest

  deploy:
    name: Deploy Docker Image
    runs-on: self-hosted

    needs: build

    steps:
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull danielstoehr/raspberry-home:latest

      - name: Stop and remove existing container
        run: |
          docker stop raspberry-home-app || true && docker rm raspberry-home-app || true

      - name: Run Docker container
        run: |
          docker run -d --name raspberry-home-app 8000:80 danielstoehr/raspberry-home
